modules/Utils/GenericBrowser/GenericBrowser_0.php

The GenericBrowser was not detecting pure text fields with overflowing text and was not activating the "expand" functionality.
If "expand" functionality switched off from User Settings the rows were shown with standard height.

Fixes GB expandable rows on missing on some overflow text fields

---

modules/Utils/GenericBrowser/GenericBrowser_0.php
modules/Utils/GenericBrowser/js/col_resizable.js
modules/Utils/RecordBrowser/RecordBrowser_0.php

Added a user resizable column functionality for the Utils_GenericBrowser module and adjusted Utils_RecordBrowser accordingly:
- fixed actions column
- exclude functionality when printing pdf
The resizable column functionality is built around the <a href="http://www.bacubacu.com/colresizable/">colResizable</a> JQuery plugin distributed under the MIT license and slightly modified to fit the purpose.
Modifications tested under EPESI 1.6.2.

Utils_GenericBrowser added resizable columns functionality

---

include/epesi.js
modules/Libs/QuickForm/QuickForm_0.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php

Enable possibility to request confirmation before leaving page and form not submitted (modifications not saved)
Added User setting for RecordBrowser where the feature is used for "add" and "edit" modes.
Included some comments for easier understanding of the concept.
Reference:
http://forum.epesibim.com/viewtopic.php?f=7&t=2758&p=10139&hilit=not+saved#p10139
EDIT:
Tested also with the check for "dirty form" concept mentioned in the forum but does not work well when form submitted but not validated.

Enable possibility to request user confirmation before leaving edit page

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

RB->switch_to_addon functionality using the addon label was not working properly when there are page_splits in the tab definition. The view was switched to the tab with one position less than expected.

Fixed switch_to_addon functionality when addon label used

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php

Added the `$more` parameter to `Utils_RecordBrowserCommon::record_link_open_tag` method to enable passing of additional `$_REQUEST` parameters (switch_to_addon for instance)

RB record link open tag more functionality

---

modules/Apps/Shoutbox/Shoutbox_0.php

I had the problem several times when trying to reply to a personal Shoutbox message I forget to select the user to reply to and send the message to all.
I believe this commit fixes the issue.

Added confirmation before sending Shoutbox message to all

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

Not sure what the idea was behind but php issues E_WARNING (2) Message: Illegal string offset 'id' when $id = null.
the modification should be checked for consistency with the idea behind (I guess $id may contain the full record as array)

[FIX] avoid error when id=null

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Issue to solve: ensure column widths in addon GB tables set by user and stored in browser local storage persist over each time the record view / addon is displayed
Background: addon GB tables are assigned random id as the module path is different on each record view and column width settings are identified by GB table id
Solution: Pass the tab name to the push_main method when a RB jump to ensure static module path in record view mode.

[UPDATE] use tab as static name when jump

---

modules/Utils/GenericBrowser/GenericBrowser_0.php
modules/Utils/GenericBrowser/js/col_resizable.js
modules/Utils/GenericBrowser/theme/default.tpl

Create and use a custom id for saving column widths. ID is based on the column names and assumes that if same group of column names set then same widths should be set.

[FIX] custom col_width_id for saving GB column widths

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

A method for a frequently used feature: a linked text with tooltip
Tooltip variable controls the display of the tooltip:
- false: no tooltip
- true: default record tooltip
- array with settings: tooltip is displayed based on the settings
The tooltip option added also to create_linked_label and create_linked_label_r methods.

[UPDATE] generic method for linked text with tooltip

---

modules/Base/Notify/NotifyCommon_0.php

Watchdog icon has been used as Watchdog adds setting options to the Base/Notify user settings

[FIX] correct display of settings icon

---

modules/Utils/RecordBrowser/RecordBrowser_0.php
modules/Utils/RecordBrowser/RecordPicker/RecordPicker_0.php

Do not change the Utils_RecordBrowser::$rb_obj in case of RecordPicker (special) display.
Otherwise the variable cannot be safely used in processing callbacks

[FIX] do not change the Utils_RecordBrowser::$rb_obj when special display

---

modules/Base/Notify/NotifyCommon_0.php
modules/CRM/Common/CommonCommon_0.php
modules/CRM/Contacts/ContactsCommon_0.php
modules/Data/Countries/CountriesCommon_0.php
modules/Utils/CommonData/CommonDataCommon_0.php
modules/Utils/CommonData/CommonData_0.php
modules/Utils/CommonData/qf.php
modules/Utils/RecordBrowser/QueryBuilderIntegration.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php

The option for commondata list ordering is now called `order`.
Legacy calls are supported for recordset field installation and using the `order_by_key` option.
The calls to `get_array` and `get_translated_array` methods of the `Utils_CommonData` class now require that `$order` argument is specifically mentioned (`key`, `position` or `value`) if not the default one (`value`).

[UPDATE] remove legacy code and make order option for commondata more intuitive

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php
modules/Utils/RecordBrowser/RecordPicker/RecordPicker_0.php
modules/Utils/RecordBrowser/rpicker.js

Allows for RecordPicker to be used on multiselect fields which support values from several recordsets and uses the presently edited record values to set selection list crits /if applicable/.

[FEATURE] RecordPicker for multiselect fields with more than one tab and crits

---

modules/CRM/Contacts/ContactsCommon_0.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php
modules/Utils/RecordBrowser/RecordPicker/RecordPicker_0.php
modules/Utils/RecordBrowser/rpicker.js

Modified the crm_company_contact_type and set it up as a standard select / multiselect field supporting 2 recordsets (company and contact).
Based on this the system uses the default QFfield_select callback and has standard parameters. The recordpicker is then supported for the multiselect fields.
Values are stored in database as RB default (__tab/record-id__)
The format callback functions are backward compatible in order to support the old field value format  (__rset-id:record-id__)
This means the existing recordsets settings can be modified to the new set up:
- delete the custom QFfield_callback
- set the field 'param' to company,contact::;::;CRM_ContactsCommon::crm_company_contact_select_list_options
If modules already installed get the field settings modified then new entries data will …

CRM_Contacts  crm_company_contact_type to use recordpicker

---

modules/CRM/Contacts/ContactsCommon_0.php

Fix the preparation of the format callback string.
There seems to be a wrong setting of crits and format callbacks in the `crm_contact_datatype` method as well. The sequence of crits and format seems reverse to what it should be.

[FIX] correct format_callback definition

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Update code for select items display:
- use description callback if available
- move tab caption routine to a single method `call_select_item_format_callback`

[UPDATE] organize display of select items

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

Introduce method to access the RB crits.
Useful when developer likes to access the filter crits for instance when using `show_filters` in an addon.

[UPDATE] method for accessing RB crits

---

modules/Libs/QuickForm/autohide_fields.js

The hidden input is also used for the static display of the form fields by assigning a hidden input id=$field.'__autohide' where $field is the control field.
Assuming hidden type is only for multiselects had broken the proper autohide / autoshow of fields when form is in view mode (static display)

[FIX] autohide for static display

---

modules/Utils/LeightboxPrompt/LeightboxPrompt_0.php

Enables again usage of empty option key for backward compatibility.

[FIX] accept empty option key

---

modules/Base/Box/BoxCommon_0.php

Using `__DIR__` does not work properly when caching of common files is enabled

[FIX] default.ini location

---

modules/Utils/Tooltip/TooltipCommon_0.php
modules/Utils/Tooltip/js/tooltip.js

Here I propose a small modification in the tooltip_id generation routine.
In my case I had to modify it as I add additional html content (expand row in a table) containing tooltips with an ajax call. Using this new method generates correct tooltip_ids for the additional html.
Probably this will not be of use in the general case but the benefit is that generation of tooltip_id is more simple and taking less space in session variable as duplicate tooltip settings have same id.

[FEATURE] change method of tooltip_id generation

---

modules/Libs/QuickForm/QuickFormCommon_0.php
modules/Libs/QuickForm/QuickForm_0.php
modules/Libs/QuickForm/autohide_fields.js

Two commits intended to solve following problems:
- if the form is initiated in a hidden element (LeightBoxPrompt for instance) autohide elements are not set up properly due to the use of `:visible` for the element to skip the routine (intended to check if element is auto-hidden). I added solution with custom class to determine if element is really auto-hidden.
- when using multiple forms with similar fields in one page (LeightBoxPrompt with several option forms) you cannot assign the field ids same as the field name so second commit is to solve that situation.
Updates are backward compatible.

[UPDATE] Libs_QuickForm__autohide

---

modules/Utils/FileStorage/FileLeightbox.php

File leightbox is created based on file meta hash which means same file displayed several times creates duplicate leightboxes.
Introduced cache to keep track of that and avoid duplication.

[FIX] multi leightbox creation

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Otherwise if recursive access is set users cannot add new records when no defaults are set and the field is empty

[FIX] if field is empty allow access

---

modules/Utils/Tooltip/js/tooltip.js

Global scope was causing incorrect tooltips displayed in case fast moving of mouse over tooltip fields.

[FIX] correct tooltip_id variable scope

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Delayed use of static property `$table_rows` was causing incorrect values to be used when recursive access defined as probably `get_access` method modifies it

[FIX] use correct field definitions when also access is defined

---

modules/Utils/Attachment/AttachmentCommon_0.php

Bug fix - we should take a link if it's available. If expire was less than 1h it leads to invalid link...

[fix] get_remote method should take old link if it's available

---

modules/Utils/FileUpload/Dropzone.php

Second commit solves issue when using dropzone in a wizard. Script is then searching for non-existent dropzone in some of the steps.

Dropzone fixes

---

modules/Utils/RecordBrowser/QueryBuilder.php

When crits are set to a boolean Utils_RecordBrowser_Crits::from_array converts them to Utils_RecordBrowser_CritsRawSQL and when passed to Utils_RecordBrowser_QueryBuilder::build_query as first argument an error is trigerred

[FIX] build_query $crits argument type declaration

---

modules/Utils/LeightboxPrompt/theme/form.css
modules/Utils/LeightboxPrompt/theme/form.tpl

If leightbox prompt has several forms then id is not a good attribute to define for the form wrappers

[FIX] replace id with class in defining form wrapper table

---

modules/Utils/ChainedSelect/ChainedSelectCommon_0.php
modules/Utils/ChainedSelect/callback.php
modules/Utils/ChainedSelect/cs.js

- introduce method for using a callback function to retrieve the chained select items
- enable using a callback or url for the default `create` method
- possibility to pass `prev_ids` parameter as string if only one previous select
- rename the jscript object to the name of the module
- add description to the `create` method

[FEATURE] introduce callback option for retrieving updated chained select items
