Telaxus/EPESI

modules/Utils/GenericBrowser/js/col_resizable.js

GB cols were not resizing properly when window resized especially from maximized to floating window

Fix for GenericBrowser colResizable

---

modules/Utils/GenericBrowser/GenericBrowser_0.php

Absolute width of dummy `<td>` is added  to the last visible `<td>` so it is correctly displayed on the TCPDF printout.

GB improve printing of dummy cells

---

modules/Libs/CKEditor/CKEditorCommon_0.php

Enable possibility to use display callback for a CKEditor edited field

Libs CKeditor display callback

---

include/database.php
include/epesi.php
include/misc.php

Display caller method for DB methods when in SQL_TIMES mode

SQL_TIMES display caller

---

modules/Libs/QuickForm/3.2.11/HTML/QuickForm/advcheckbox.php
modules/Libs/QuickForm/QuickFormCommon_0.php
modules/Libs/QuickForm/QuickForm_0.php
modules/Libs/QuickForm/autohide_fields.js

Enables quick setup for autohide / autoshow of fields depending on a select / checkbox field value.
Some more details will be added to the forum.

[FEATURE] Libs_QuickForm autohide / autoshow fields

---

modules/CRM/Contacts/ContactsCommon_0.php
modules/CRM/Contacts/ContactsInstall.php
modules/CRM/Contacts/patches/20160124_field_link_callbacks.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Common method to use as display callback when a field value is linked to open record in view mode

[UPDATE] method to create linked field label

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

Recordbrowser quick new record save shortcut

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php
modules/Utils/RecordBrowser/RecordPicker/RecordPicker_0.php
modules/Utils/RecordBrowser/theme/Record_picker.tpl

enable selection of records using ReckordPicker for multiselect fields enabled for multiple recordsets

[FEATURE] enable selection of records using ReckordPicker from multiple recordsets

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Introduce also consistency in variable naming

[UPDATE] introduce default display callbacks

---

modules/Utils/Attachment/Attachment_0.php

Also improve column naming consistency

[UPDATE] include file name in file access history

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Refactoring of the handling of select fields
- moved params decode logic to a single method
- moved record token decode to one method (single or multi tab)
- moved crits creation (based callback and access) to separate method
- moved the formatting of select option to separate method (calling custom or the default option format callback)
- QFfield select options include $record[$field] value. System seems to function without it this but kept the code for compatibility

[UPDATE] refactor select field handling

---

modules/CRM/PhoneCall/PhoneCallCommon_0.php
modules/CRM/PhoneCall/PhoneCallInstall.php
modules/CRM/PhoneCall/js/main.js
modules/CRM/PhoneCall/patches/20160725_refactor_field_control.php

[UPDATE] form control refactor to jquery

---

modules/Utils/RecordBrowser/QueryBuilderIntegration.php

A bit of update and refactoring separated in two commits:
- use the `Utils_RecordBrowserCommon::select_param_decode` method
- refactor code with variable renaming for consistency

[UPDATE] QBIntegration  use select_param_decode

---

modules/Utils/QueryBuilder/QueryBuilder_0.php

Introduce method that can add/insert filters to the QueryBuilder

[UPDATE] introduce add_filter method

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Pure refactoring with change of name only to keep code consistency

[UPDATE] rename variables to $desc for consistency

---

modules/Utils/LeightboxPrompt/LeightboxPromptCommon_0.php
modules/Utils/LeightboxPrompt/LeightboxPrompt_0.php
modules/Utils/LeightboxPrompt/js/jquery-deparam.js
modules/Utils/LeightboxPrompt/js/leightbox_prompt.js

Refactor Utils_LeightboxPrompt module:
- separate jscript
- refactor jscript to jquery
- tidy up php code

[UPDATE] refactor Utils_LeightboxPrompt to jquery

---

modules/Utils/RecordBrowser/RecordBrowserInstall.php

[FIX] require RB filters module for installation

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

[FIX] access using callbacks

---

modules/Utils/RecordBrowser/Crits.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Utils_RecordBrowser__rename_field_change_crits_field

---

modules/Utils/FileStorage/FileStorageCommon_0.php

Fixes cases where:
- file is not copied but DB entry made. On trying to upload again system throws duplicate DB key
- if for some reason above has happened now the system just writes the new file and does not try to insert another DB record

[FIX] file writing

---

modules/Utils/RecordBrowser/QueryBuilder.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php
modules/Utils/RecordBrowser/RecordBrowser_0.php
modules/Utils/RecordBrowser/theme/required_crits_to_add.tpl

- refactor get_access method
- include grant/restrict feature for callbacks for #133 
Tested with Tests/RecordBrowser and custom access callbacks

[UPDATE] refactor Utils_RecordBrowserCommon::get_access method

---

include/session.php

[FIX] memcached session lock when session expired

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Method was raising error on calculated fields without DB entries. Fixed this by skipping the `RenameColumn` routine for fields where there is no column.
Also `$crits->find($id)` returns `null` if crits is created from an empty array so check if crits is empty and skip the loop.
Alternatively `$crits->find($id)` might return `array()` if nothing found but not sure if this will not break some other code.

[FIX] renaming fields without DB entries

---

modules/Utils/FileStorage/FileLeightbox.php

Use `microtime` instead of static variable

[FIX] multi leightbox creation

---

modules/Utils/FileUpload/Dropzone.php
modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

Enable defining accepted files

[FEATURE] accepted files option

---

modules/Utils/RecordBrowser/theme/View_entry.css

[FIX] file attachments display

---

modules/Utils/RecordBrowser/RecordBrowserCommon_0.php

This enables use of single callback for several tabs. Useful when there is dynamic tab selection from user interface.

[UPDATE] pass tab as argument on processing callback

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

Copied from bootstrap/master branch

[FIX] quickjump

---

modules/Utils/RecordBrowser/RecordBrowser_0.php

[FIX] column visibility if no records

---

modules/Utils/Watchdog/WatchdogCommon_0.php
modules/Utils/Watchdog/Watchdog_0.php

so you can set more than one applet for groups of recordsets and you know which applet is for what.

[FEATURE] set watchdog applet title, 

---

modules/Utils/CommonData/CommonDataCommon_0.php

[fix] sql error

---

modules/Applets/Clock/ClockCommon_0.php
modules/Applets/Clock/Clock_0.php

Since long time in use in my company, just found the time to share it with the world

[FEATURE] introduce double clock

---

modules/Base/Dashboard/Dashboard_0.php

[FIX] correctly handle misconfigured custom applets

---

modules/Base/Notify/NotifyCommon_0.php
modules/Base/Notify/js/desktop-notify.js
modules/Base/Notify/js/main.js
modules/Base/Notify/refresh.php

Fix:
- correct setting of "working" variable considering scope as otherwise notifications were never shown
- new line char on jscript alert
Update:
- use browser generic Notification with HTML5 Notification by Tsvetan Tsvetkov

Base notify fix + update
